version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQL_DB=rate_server
      - SQL_HOST=db
      - SQL_PORT=3306
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1 #this is just for demo purposes 
    command: sh -c "bundle exec rake db:drop && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s" 
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      # The db_setup.sql script is used to create the neccessary databases for MySQL 
      # Allowing the rails application to connect to the server and seed the data
      - ./db/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    ports:
      - "3306:3306"
